spring:
  aop:
    proxy-target-class: true
  application:
    name: reservation
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/common
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cache :
    type : redis
    host : localhost
    port : 6379


cache:
  ttl:
    users: 10800000
    roles: 108000000
    default: 10800000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true



interface:
  common-portal :
    url : http://openapi.seoul.go.kr:8088
    key : 724c746457716b7236367641416775

security:
  jwt:
    secret: "mySecretKeyForJwtTokenExample2025"
    expiration: 86400000 # 1일 (24시간)