spring:
  aop:
    proxy-target-class: true
  application:
    name: reservation
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/common
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cache :
    type : redis
    host : localhost
    port : 6379


cache:
  ttl:
    users: 10800000
    roles: 108000000
    default: 10800000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true



interface:
  common-portal :
    url : http://openapi.seoul.go.kr:8088
    key : 724c746457716b7236367641416775

  kakao:
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    client-id: eb8b52c80a1ad936a2de2f1ff863ccb2
    redirect-uri: https://localhost:8080/api/auth/kakao/signup

security:
  jwt:
    secret: "mySecretKeyForJwtTokenExample2025"
    expiration: 86400000 # 1일 (24시간)

mail:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL_USERNAME}  # 환경변수 사용
  password: ${EMAIL_PASSWORD}  # 환경변수 사용
  properties:
    mail:
      smtp :
        auth: true
        starttls:
          enable: true
  transport:
    protocol: smtp
  debug: true

file:
  upload-dir : C:\image
