spring :
  application :
      name : demo
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  springdoc :
    api-docs :
      path : /api-docs
    swagger-ui :
      path : /swagger-ui
      operations-sorter: method
