spring:
  cache :
    type : redis
    host : localhost
    port : 6379
  application :
    name : core
  datasource:
    url: jdbc:mariadb://localhost:3306/
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui
      operations-sorter: method

interface:
  common-portal :
    url : http://openapi.seoul.go.kr:8088
    key : 724c746457716b7236367641416775
